herro murkup
cel3ntano/project-vegetables24 pull request #1
Opened 2024-02-28 11:52 UTC by AnnaHodunko

2024-02-28 23:56 UTC, cel3ntano requested changes
Аню, дякую за PR, додав коментарі до деяких рядків, на які потрібно звернути увагу. 
На даний момент переглядав лише базові стилі, враховуючи коментарі, передивись, будь ласка, і внеси відповідні зміни і в адаптивні стилі, якщо потрібно

2024-02-28 23:56 UTC, andrii-zhygalko commented on src/css/hero.css
> +  margin-left: auto;
Так як у нас вже задана властивість `margin: o auto`; для класу `section`, ця властивість буде надлишковою

2024-02-28 23:56 UTC, andrii-zhygalko commented on src/css/hero.css
> +  margin-right: auto;
Так як у нас вже задана властивість `margin: o auto`; для класу `section`, ця властивість буде надлишковою

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +    display: block;
Параграф є блочним елементом за замовчуванням, тому ця властивість буде надлишковою

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +    text-align: start;
Тут потрібно використати значення left замість start. Це не є грубою помилкою, і візуально різниці не буде, проте в нас немає тексту із змінними напрямками, тому left буде більш коректним

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +    height: 90px;
Не потрібно обмежувати параграф по висоті, він сам займе необхідну йому висоту

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +    width: 335px;
Знову ж таки, тут не потрібно задавати  фіксовану ширину, щоб параграф міг стискатись при ширині, меншій за `375px`

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +  margin: 0 auto 20px auto;
В даному випадку заголовку подрібний лише маржин знизу, щоб відштовхнути від себе параграф

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +  display: block;
Заголовок є блочним елементом за замовчуванням, тому ця властивість буде надлишковою

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +  height: 192px;
Також, не потрібно обмежувати заголовок по висоті, він сам займе необхідну йому висоту

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +  width: 335px;
Не потрібно задавати заголовку фіксовану ширину, щоб він міг стискатись при ширині меншій за `375px`

2024-02-28 23:56 UTC, cel3ntano commented on src/css/hero.css
> +  max-width: 320px;
Так як по ТЗ у нас верстка має бути "гумова" до `375px`, маємо обмежити ширину цієї секції через `max-width: 375px;`, тобто ми кажемо, що до 375 можеш бути "гумовв", але ширше - ні.

2024-02-28 23:59 UTC, closed without merging

2024-02-29 11:09 UTC, AnnaHodunko commented on src/css/hero.css
> +  max-width: 320px;
Привіт. Дякую, за твою роботу та виправлення. Наче все підтягнула