Header menu
cel3ntano/project-vegetables24 pull request #15
Opened 2024-03-01 10:49 UTC by Olena000

2024-03-01 19:35 UTC, cel3ntano requested changes
Олено, дякую за PR, передивись будь ласка коментарі, якщо будуть питання, пиши в чаті або тут. Після цих змін потрібно буде передивитись мобільне меню, там дещо може зміститись. Чекатиму новий PR

2024-03-01 19:35 UTC, andrii-zhygalko commented on src/partials/header.html
>              <a class="header-menu-link" href="./header.html">Vegetables</a>
Запитай будь ласка, хто які `id` додав у свої секції, і внеси відповідні зміни до посилань

2024-03-01 19:35 UTC, cel3ntano commented on src/partials/header.html
У рядку  ```<div class="container header-container">``` додатковий клас ```header-container``` можна прибрати, а у стилях до селектору ```header``` потрібно додати ```.container```, щоб спрацювало обмеження контейнеру по ширині, інакше він тягнеться до країв екрану, а нам цього не потрібно.

Тобто у стилях це виглядатиме так:  
```
.header .container {
  background-color: #576f35;
  padding-top: 20px;
  padding-bottom: 48px;
  display: flex;
}
```
Цей  ```display: flex;``` перекочував сюди із ```.header-container```, тому той селектор можна видалити взагалі.

Відповідні зміни потрібно буде внести і в медіа-запитах, щоб поправити падінги, враховучи, що ми змінили селектор.

2024-03-01 19:35 UTC, cel3ntano commented on src/css/header.css
>    .header {
Враховуючи коментар по HTML, тут потрібно додати ще один селектор, а саме `.container`, щрб спрацювали стилі

2024-03-01 19:35 UTC, cel3ntano commented on src/css/header.css
> +    height: 52px;
ВИсоту можна прибрати, хедер займе необхідну йому висоту сам по собі

2024-03-01 19:35 UTC, cel3ntano commented on src/css/header.css
> +    margin-bottom: 154px;
Падінги можна перевизначити як  padding: 0 100px;, щоб по боках були відступи по 100px, як за макетом, а зверху ми зробили відступ через абсолют. Щодо відступу вниз, можна прибрати, він буде зроблений уже у секції Hero через margin.

2024-03-01 23:45 UTC, cel3ntano commented on src/css/header.css
> +    left: 0;
Для того, щоб відцентрувати хедер по горизонталі, можемо використати
```
left: 50%; 
transform: translateX(-50%);
```

2024-03-02 02:42 UTC, closed without merging

2024-03-02 03:29 UTC, cel3ntano commented
Олено, залишимо поки ширину хедеру як є (там де я писав про клас header-container), внеси будь ласка правки тільки щодо десктопу, де я писав про відступи і центрування. Щодо його ширини уточню у ментора.

2024-03-02 10:43 UTC, Olena000 commented
Привіт. Дякую за твою роботу! 
А падінги топ і ботом на хедері в таблеті і мобільній я правильно прописала? Взагалі з хедера в цих версіях повинен бути падінг вниз?

2024-03-02 10:48 UTC, Olena000 commented
![Снимок экрана 2024-03-02 124433](https://github.com/cel3ntano/project-vegetables24/assets/154604010/20ed9cac-eee9-4bcd-bfba-02e0386f6121)
Наприклад, тут 50рх у мене прописано як падінг. Чомусь я сумніваюсь, що має бути так...

2024-03-02 13:36 UTC, cel3ntano commented
Олено, тут можна реалізувати по-різному. Твій варіант з падінгами цілком робочий, як на мене. А секцію hero просто приліпимо знизу без відступів та і все.

Звичайно, можна зробити margin-bottom від хедера, або margin-top від hero, все це - варіанти. Ти вирішила так, чому б ні. Якщо ментор зробить зауваження, що ж, переробимо, така наша студентська доля.

2024-03-02 13:40 UTC, cel3ntano commented
Щодо обмеження фону хедеру контейнером є відповідь, то ж потрібно внести усі правки, як писав вище 
![image](https://github.com/cel3ntano/project-vegetables24/assets/160436964/ddee35a7-f513-4a4c-b88b-8e7f697756f5)

2024-03-02 13:43 UTC, cel3ntano commented
Також, зроби, будь ласка усі нові правки у новій гілці. Тобто, онови main у своїй поточній гілці `(branch>update from main)` та створи нову гілку на базі поточної. Попрактикуємось створювати інші гілки і створювати нові PR. Ще раз дякую за активну роботу та своєчасність, ти - молодець :)

2024-03-02 15:53 UTC, Olena000 commented
Добре, все зрозуміло) я сьогодні дороблю все і відправлю тобі PR. Дякую за допомогу 🤗