Hero section
cel3ntano/project-vegetables24 pull request #8
Opened 2024-02-29 11:20 UTC by AnnaHodunko

2024-02-29 20:38 UTC, cel3ntano requested changes
Аню, дякую за виправлення. Є ще невеликі зміни, переглянь будь ласка

2024-02-29 20:38 UTC, andrii-zhygalko commented on src/css/hero.css
> +    width: 335px;
Не потрібно обмежувати параграф по ширині, щоб він міг стискатися при ширині екрану меншій за `375px`

2024-02-29 20:38 UTC, andrii-zhygalko commented on src/css/hero.css
> +  background: var(--Background, #576F35);
Для чистоти коду функцію var можна прибрати і в цьому рядку і у всіх інших, так як ми не використовуємо у проекті css змінні (css variables) для кольорів

2024-02-29 20:38 UTC, andrii-zhygalko commented on src/css/hero.css
> +    width: 704px;
Не є помилкою, але заголовок і так стане як потрібно завдяки падінгам контейнеру, ширину можна прибрати

2024-02-29 20:38 UTC, andrii-zhygalko commented on src/css/hero.css
> +  .hero-title {
За макетом, у планшетній версії заголовок відштовхує параграф на `25px`

2024-02-29 20:38 UTC, andrii-zhygalko commented on src/css/hero.css
> +  font-family: "Inter Tight";
font-family у нас наслідується від styles.css, можна прибрати тут і в інших рядках

2024-02-29 20:38 UTC, cel3ntano commented on src/css/hero.css
> +    margin-top: 172px;
Цей маржин поки що залишимо як є, просто звуртаю увагу, що коли буде готовий хедер, можливо треба буде змінити цей маржин, бо хедер буде забраний з потоку, і заголовок може зміститись

2024-02-29 20:38 UTC, cel3ntano commented on src/css/hero.css
> +    gap: 128px;
Можна цей геп прибрати, а для того, щоб відштовхнути параграф просто превизначити margin-bottom, який був до цього 25px у планшетній версії (див. коментар про заголовок у планшетній версії)

2024-02-29 22:08 UTC, cel3ntano requested changes

2024-02-29 22:08 UTC, cel3ntano commented on src/css/hero.css
>    padding: 100px 0 0 0;
Падінг поки прибираємо, відступ буде зроблений за рахунок header (поки що так, далі будемо дивитись)

2024-02-29 22:08 UTC, cel3ntano commented on src/css/hero.css
>      padding: 122px 0 0 0;
Падінг поки прибираємо, відступ буде зроблений за рахунок header (поки що так, далі будемо дивитись)

2024-03-01 05:50 UTC, AnnaHodunko commented on src/css/hero.css
> +    margin-top: 172px;
ок, зрозуміла.

2024-03-01 05:50 UTC, AnnaHodunko commented on src/css/hero.css
> +  font-family: "Inter Tight";
добре

2024-03-01 05:50 UTC, AnnaHodunko commented on src/css/hero.css
> +  .hero-title {
точно, не звернула увагу

2024-03-01 05:51 UTC, AnnaHodunko commented on src/css/hero.css
> +    width: 704px;
просто пам'ятаю ми на домашці наче ставили

2024-03-01 05:53 UTC, AnnaHodunko commented on src/css/hero.css
> +    gap: 128px;
я зробила їх флесами, бо маржанами і підінгами не змогла поставити у те положення, шо треба. це тільки на декстопі так

2024-03-01 06:00 UTC, AnnaHodunko commented on src/css/hero.css
>    padding: 100px 0 0 0;
я прибрала падінги і фон змістився, не можу зрозуміти, яку висоту тепер треба задати

2024-03-02 01:50 UTC, cel3ntano reviewed
Аню, відписав щодо правок, прошу створити нову гілку, і робити правки вже в ній, і відповідно з нової гілки робити PR. Не забудь оновити main, і створи нову гілку на базі цієї. Гарного дня!

2024-03-02 01:50 UTC, andrii-zhygalko commented on src/css/hero.css
> +  background-image: linear-gradient(0deg, rgba(20, 20, 20, 0.20) 0%, rgba(20, 20, 20, 0.20) 100%), url(../img/hero/hero-mob-1x.jpg);
Треба поправити шляхи до фонових картинок. На початку шляху залишити тільки `/` (не `../`)

2024-03-02 01:50 UTC, andrii-zhygalko commented on src/css/hero.css
> +  /* padding: 100px 0 0 0; */
Потрібно перевизначити padding для секції, бо вона в нас "прилипає" зверху до хедеру, а знизу до секції _How it works_.
Просто запишемо `padding: 0;`, і відступ зверху і знизу прибереться

2024-03-02 01:50 UTC, andrii-zhygalko commented on src/css/hero.css
> +  height: 812px;
Так як ми обнулили падінг, висоту треба змінити відповідно, і вона стане `712px`.

2024-03-02 01:50 UTC, cel3ntano commented on src/css/hero.css
> +  background-image: linear-gradient(0deg, rgba(20, 20, 20, 0.20) 0%, rgba(20, 20, 20, 0.20) 100%), url(../img/hero/hero-mob-1x.jpg);
Давай поки що приберемо всюди градієнти, і залишимо тільки картинку, бо з градієнтом змінюється верхній колір секції 
<img width="145" alt="image" src="https://github.com/cel3ntano/project-vegetables24/assets/160436964/60c10b45-efbc-48bb-b630-bd35ef51ebc0">

2024-03-02 01:50 UTC, cel3ntano commented on src/css/hero.css
> +    height: 1024px;
Тепер, враховуючи інші зміни, потрібно скоригувати висоту секції для планшету на `902px`

2024-03-02 01:50 UTC, cel3ntano commented on src/css/hero.css
> +    margin-top: 172px;
Врахочуючи, що хедер в десктопі буде спозиціонований абсолютом, маржин потрібно задати від самого верху, отже верхній маржин буде `238px`

2024-03-02 01:50 UTC, cel3ntano commented on src/css/hero.css
> +  .hero-title {
Цей маржин 25px на планшеті, для того щоб не обнуляти його на десктопі (бо він унаслідується), потрібно закрити в медіа-запит таким чином, щоб він не застосовувався на десктопі. Підказка: min width 768px та max width 1279px.

2024-03-02 01:50 UTC, cel3ntano commented on src/css/hero.css
> +  .hero-title {
Також цей маржин, треба обнуляти на десктопі (бо він унаслідується).
Ще є варіант застосовувати специфічні стилі, закриті у певному діапазоні від min width до max width, але поки що підемо простим шляхом і обнулимо його на десктопі.

2024-03-02 01:50 UTC, closed without merging